version: '3.7'

services:

    shop:
        image: ${DOCKER_REGISTRY-}customer
        networks:
            - default
        build:
            context: .
            dockerfile: ./Mc2.CrudTest.Presentation/Service/Dockerfile
            
    sqldb:
        image: mcr.microsoft.com/mssql/server:2022-latest
        networks:
            - default
networks: 
     default: 
       external: true
       name: appliance 


    

  